# Very basic Travis CI (http://travis-ci.org) control file that allows
# some basic Linux-based continuous integration testing (for free).

language: c

# Before setting up the source tree, install necessary development
# headers
before_install: >

  sudo apt-get update

  sudo apt-get install -y \
    libx11-dev libgtk2.0-dev autopoint libgettextpo-dev libstroke0-dev \
    guile-2.0-dev flex bison groff texinfo python2.7-dev

# Set up the source tree by fetching Linux-specific prebuilt objects
install: ./autogen.sh && ./configure --disable-update-xdg-database -with-x=yes

after_failure: ./travis-after-failure.sh

# Start the Virtual X Framebuffer
services:
  - xvfb

# Bootstrap the LCB compiler, build the default target set and run a
# the default test suite.
script: make -s all check
